services:
  www:
    build:
      context: ./www
      dockerfile: Dockerfile
    container_name: www
    init: true
    volumes:
      - ../:/var/www
    ports:
      - "9003:9003"
    command: sleep infinity
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/config:/etc/nginx/conf.d/
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ../:/var/www
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - www
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "9010:9010"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - APACHE_HTTP_PORT_NUMBER=9010
    networks:
      - app-network
    command: /bin/bash -c "sed -i \"s/80/$$APACHE_HTTP_PORT_NUMBER/g\" /etc/apache2/sites-available/000-default.conf /etc/apache2/ports.conf && /docker-entrypoint.sh apache2-foreground"

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - TZ=America/Sao_Paulo
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge